-- Shah Lalji Nangpar Academy website
-- Run this once in Supabase Dashboard > SQL Editor after creating the admin
-- user lawrencengugi@shahlalji.ac.ke in Authentication > Users.

create table if not exists public.stories (
  id bigint generated by default as identity primary key,
  slug text not null unique check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  category text not null check (char_length(category) between 1 and 80),
  title text not null check (char_length(title) between 1 and 140),
  excerpt text not null check (char_length(excerpt) between 1 and 500),
  hero_image text not null check (char_length(hero_image) between 1 and 500),
  hero_alt text not null check (char_length(hero_alt) between 1 and 220),
  read_time text not null default '4 minute read',
  quote text not null default '',
  body_json jsonb not null default '[]'::jsonb
    check (jsonb_typeof(body_json) = 'array'),
  status text not null default 'draft'
    check (status in ('draft', 'published')),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists stories_status_updated_idx
  on public.stories (status, updated_at desc);

create table if not exists public.enquiries (
  id bigint generated by default as identity primary key,
  parent_name text not null check (char_length(parent_name) between 1 and 120),
  email text not null check (char_length(email) between 3 and 160),
  phone text not null check (char_length(phone) between 3 and 60),
  child_age text not null check (char_length(child_age) between 1 and 40),
  year_group text not null check (char_length(year_group) between 1 and 80),
  message text not null check (char_length(message) between 1 and 1200),
  status text not null default 'new'
    check (status in ('new', 'in_progress', 'closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists enquiries_status_created_idx
  on public.enquiries (status, created_at desc);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  slug text not null unique check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  title text not null check (char_length(title) between 1 and 140),
  summary text not null check (char_length(summary) between 1 and 500),
  description text not null check (char_length(description) between 1 and 4000),
  location text not null check (char_length(location) between 1 and 180),
  starts_at timestamptz not null,
  ends_at timestamptz check (ends_at is null or ends_at >= starts_at),
  image_url text not null check (image_url like '/images/%' or image_url like 'https://%'),
  image_alt text not null check (char_length(image_alt) between 1 and 220),
  status text not null default 'draft' check (status in ('draft', 'published')),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists events_published_starts_idx
  on public.events (starts_at)
  where status = 'published';

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists stories_set_updated_at on public.stories;
create trigger stories_set_updated_at
before update on public.stories
for each row execute function public.set_updated_at();

drop trigger if exists enquiries_set_updated_at on public.enquiries;
create trigger enquiries_set_updated_at
before update on public.enquiries
for each row execute function public.set_updated_at();

drop trigger if exists events_set_updated_at on public.events;
create trigger events_set_updated_at
before update on public.events
for each row execute function public.set_updated_at();

alter table public.stories enable row level security;
alter table public.enquiries enable row level security;
alter table public.events enable row level security;

drop policy if exists "published stories are public" on public.stories;
create policy "published stories are public"
on public.stories for select
to anon, authenticated
using (status = 'published');

drop policy if exists "admins can read every story" on public.stories;
create policy "admins can read every story"
on public.stories for select
to authenticated
using (((select auth.jwt()) -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "admins can create stories" on public.stories;
create policy "admins can create stories"
on public.stories for insert
to authenticated
with check (
  ((select auth.jwt()) -> 'app_metadata' ->> 'role') = 'admin'
  and created_by = (select auth.uid())
);

drop policy if exists "admins can update stories" on public.stories;
create policy "admins can update stories"
on public.stories for update
to authenticated
using (((select auth.jwt()) -> 'app_metadata' ->> 'role') = 'admin')
with check (((select auth.jwt()) -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "admins can delete stories" on public.stories;
create policy "admins can delete stories"
on public.stories for delete
to authenticated
using (((select auth.jwt()) -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "any visitor can submit an enquiry" on public.enquiries;
create policy "any visitor can submit an enquiry"
on public.enquiries for insert
to anon, authenticated
with check (true);

drop policy if exists "admins can read enquiries" on public.enquiries;
create policy "admins can read enquiries"
on public.enquiries for select
to authenticated
using (((select auth.jwt()) -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "admins can update enquiries" on public.enquiries;
create policy "admins can update enquiries"
on public.enquiries for update
to authenticated
using (((select auth.jwt()) -> 'app_metadata' ->> 'role') = 'admin')
with check (((select auth.jwt()) -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "admins can delete enquiries" on public.enquiries;
create policy "admins can delete enquiries"
on public.enquiries for delete
to authenticated
using (((select auth.jwt()) -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "published events are public" on public.events;
create policy "published events are public"
on public.events for select
to anon, authenticated
using (status = 'published');

drop policy if exists "admins can read every event" on public.events;
create policy "admins can read every event"
on public.events for select
to authenticated
using (((select auth.jwt()) -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "admins can create events" on public.events;
create policy "admins can create events"
on public.events for insert
to authenticated
with check (
  ((select auth.jwt()) -> 'app_metadata' ->> 'role') = 'admin'
  and created_by = (select auth.uid())
);

drop policy if exists "admins can update events" on public.events;
create policy "admins can update events"
on public.events for update
to authenticated
using (((select auth.jwt()) -> 'app_metadata' ->> 'role') = 'admin')
with check (((select auth.jwt()) -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "admins can delete events" on public.events;
create policy "admins can delete events"
on public.events for delete
to authenticated
using (((select auth.jwt()) -> 'app_metadata' ->> 'role') = 'admin');

revoke all on table public.stories from anon, authenticated;
revoke all on table public.enquiries from anon, authenticated;
revoke all on table public.events from anon, authenticated;
grant select on table public.stories to anon, authenticated;
grant insert, update, delete on table public.stories to authenticated;
grant insert on table public.enquiries to anon, authenticated;
grant select, update, delete on table public.enquiries to authenticated;
grant select on table public.events to anon, authenticated;
grant insert, update, delete on table public.events to authenticated;
grant usage, select on sequence public.stories_id_seq to authenticated;
grant usage, select on sequence public.enquiries_id_seq to anon, authenticated;
grant usage, select on sequence public.events_id_seq to authenticated;

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'story-images',
  'story-images',
  true,
  10485760,
  array['image/jpeg', 'image/png', 'image/webp', 'image/avif']
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "story images are public" on storage.objects;
create policy "story images are public"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'story-images');

drop policy if exists "admins can upload story images" on storage.objects;
create policy "admins can upload story images"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'story-images'
  and ((select auth.jwt()) -> 'app_metadata' ->> 'role') = 'admin'
);

drop policy if exists "admins can replace story images" on storage.objects;
create policy "admins can replace story images"
on storage.objects for update
to authenticated
using (
  bucket_id = 'story-images'
  and ((select auth.jwt()) -> 'app_metadata' ->> 'role') = 'admin'
)
with check (
  bucket_id = 'story-images'
  and ((select auth.jwt()) -> 'app_metadata' ->> 'role') = 'admin'
);

drop policy if exists "admins can delete story images" on storage.objects;
create policy "admins can delete story images"
on storage.objects for delete
to authenticated
using (
  bucket_id = 'story-images'
  and ((select auth.jwt()) -> 'app_metadata' ->> 'role') = 'admin'
);

insert into public.stories (
  slug, category, title, excerpt, hero_image, hero_alt,
  read_time, quote, body_json, status
)
values
(
  'learning-through-discovery',
  'Early Years',
  'Learning Through Discovery',
  'How purposeful, hands-on experiences help young learners build language, confidence and curiosity from the very beginning.',
  '/images/school/early-years-fruit-learning.webp',
  'Teachers and Early Years learners exploring fruit in the classroom',
  '4 minute read',
  'When children can touch, talk, compare and create, learning becomes something they understand—not simply something they are told.',
  $story$[
    {
      "heading": "Learning begins with curiosity",
      "paragraphs": [
        "In Early Years, the most meaningful questions often begin with something familiar. A piece of fruit, a colour, a sound or a story can become the starting point for language, number, observation and conversation.",
        "Purposeful activities give young learners room to notice differences, describe what they see and make connections with the world around them. The teacher guides the experience while each child remains an active participant."
      ],
      "image": "/images/school/early-years-fruit-learning.webp",
      "imageAlt": "Early Years learners choosing and discussing fruit with their teachers"
    },
    {
      "heading": "Confidence grows through participation",
      "paragraphs": [
        "Young children build confidence by trying, responding and sharing ideas in a supportive setting. Whether they are exploring food, dressing for a careers activity or practising a new movement, participation helps them develop independence.",
        "These moments also strengthen social learning. Children take turns, listen to one another and discover that their contributions matter within the group."
      ],
      "image": "/images/school/careers-day.webp",
      "imageAlt": "Young learners dressed for different careers during a school activity"
    },
    {
      "heading": "A foundation for the journey ahead",
      "paragraphs": [
        "The Early Years experience is designed to prepare children for far more than the next classroom. Curiosity, communication, self-belief and the ability to work with others form a foundation that supports every later stage of learning.",
        "At SLNA, those foundations grow within one connected community, allowing learners to move forward with familiarity, encouragement and a growing sense of possibility."
      ],
      "image": "/images/school/early-years-taekwondo.webp",
      "imageAlt": "Early Years learners practising taekwondo together"
    }
  ]$story$::jsonb,
  'published'
),
(
  'confidence-to-compete',
  'Sport',
  'Confidence to Compete',
  'Sport gives learners a practical language for discipline, teamwork, resilience and the courage to keep improving.',
  '/images/school/swimming-competition.webp',
  'SLNA swimmers competing in marked lanes during a school event',
  '5 minute read',
  'Competition matters, but the deeper success is learning how to prepare, respond and return stronger.',
  $story$[
    {
      "heading": "More than a result",
      "paragraphs": [
        "A race, match or training session makes progress visible. Learners can feel the effect of preparation, understand where technique matters and recognise that improvement is built through consistent effort.",
        "Sport also teaches young people how to respond when an outcome is not what they hoped for. Reflection, composure and the decision to try again are valuable far beyond the field, court or pool."
      ],
      "image": "/images/school/swimming-training.webp",
      "imageAlt": "Three learners practising their swimming strokes in the school pool"
    },
    {
      "heading": "Belonging to a team",
      "paragraphs": [
        "Team environments ask learners to communicate, trust one another and understand their role within a shared goal. They learn when to lead, when to support and how individual effort contributes to collective performance.",
        "The friendships and school spirit that grow through sport help learners feel connected to the wider academy community."
      ],
      "image": "/images/school/basketball-team.webp",
      "imageAlt": "The school basketball team gathered on the indoor court"
    },
    {
      "heading": "Strength that transfers",
      "paragraphs": [
        "The habits developed through sport—focus, discipline, courage and respect—support learning in every setting. Learners become more comfortable receiving feedback, setting goals and working patiently towards them.",
        "By offering varied activities, SLNA gives more young people the opportunity to find a discipline that challenges them and a community in which they can grow."
      ],
      "image": "/images/school/cycling-club.webp",
      "imageAlt": "Learners standing with their bicycles during an outdoor cycling activity"
    }
  ]$story$::jsonb,
  'published'
),
(
  'learning-beyond-the-classroom',
  'School Life',
  'Learning Beyond the Classroom',
  'Visits, creative projects and shared experiences help learners connect knowledge with the wider world.',
  '/images/school/museum-learning-trip.webp',
  'Senior learners taking part in an educational museum visit',
  '4 minute read',
  'A powerful learning experience changes the way a learner sees a subject—and sometimes the way they see themselves.',
  $story$[
    {
      "heading": "Experience gives knowledge context",
      "paragraphs": [
        "Classroom learning provides essential structure, but new environments can make ideas feel immediate. Educational visits encourage learners to observe closely, ask different questions and connect subject knowledge with real places and experiences.",
        "Being away from the usual classroom also asks students to manage themselves, collaborate and represent their school with maturity."
      ],
      "image": "/images/school/museum-learning-trip.webp",
      "imageAlt": "Senior learners collaborating during an educational museum visit"
    },
    {
      "heading": "Creativity makes thinking visible",
      "paragraphs": [
        "Creative work gives learners another way to process ideas and communicate what they understand. Making, performing and presenting require imagination, decision-making and the confidence to share something personal.",
        "The finished piece matters, but so does the process: testing an idea, adapting it and learning how to turn an intention into something others can see."
      ],
      "image": "/images/school/creative-arts-masks.webp",
      "imageAlt": "Learners presenting colourful masks they created during an arts activity"
    },
    {
      "heading": "Community is part of the curriculum",
      "paragraphs": [
        "Assemblies, clubs, trips and shared events help learners understand that school is a community as well as a place of study. They create opportunities to listen, contribute and recognise the experiences of others.",
        "Together, these moments build belonging and give young people more ways to discover their interests, strengths and responsibilities."
      ],
      "image": "/images/school/campus-assembly.webp",
      "imageAlt": "SLNA learners gathered for an assembly in the school courtyard"
    }
  ]$story$::jsonb,
  'published'
)
on conflict (slug) do nothing;

-- Dashboard authorization is stored in app_metadata, which users cannot edit.
update auth.users
set raw_app_meta_data =
  coalesce(raw_app_meta_data, '{}'::jsonb) || '{"role":"admin"}'::jsonb
where lower(email) = lower('lawrencengugi@shahlalji.ac.ke');

notify pgrst, 'reload schema';
